/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CopsmartRouteImport } from './routes/copsmart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiNotifyRouteImport } from './routes/api/notify'
import { Route as AuthedVehiclesRouteImport } from './routes/_authed/vehicles'
import { Route as AuthedTrainingRouteImport } from './routes/_authed/training'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedRosterRouteImport } from './routes/_authed/roster'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedResourcesRouteImport } from './routes/_authed/resources'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedFormsRouteImport } from './routes/_authed/forms'
import { Route as AuthedDispatchRouteImport } from './routes/_authed/dispatch'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthedSchedulePrintRouteImport } from './routes/_authed/schedule.print'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminUnitComparisonRouteImport } from './routes/_authed/admin/unit-comparison'
import { Route as AuthedAdminMigrationRouteImport } from './routes/_authed/admin/migration'
import { Route as AuthedAdminHoursReportRouteImport } from './routes/_authed/admin/hours-report'
import { Route as AuthedAdminAnnouncementsRouteImport } from './routes/_authed/admin/announcements'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CopsmartRoute = CopsmartRouteImport.update({
  id: '/copsmart',
  path: '/copsmart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyRoute = ApiNotifyRouteImport.update({
  id: '/api/notify',
  path: '/api/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVehiclesRoute = AuthedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrainingRoute = AuthedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRosterRoute = AuthedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesRoute = AuthedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFormsRoute = AuthedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDispatchRoute = AuthedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSchedulePrintRoute = AuthedSchedulePrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AuthedScheduleRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUnitComparisonRoute =
  AuthedAdminUnitComparisonRouteImport.update({
    id: '/admin/unit-comparison',
    path: '/admin/unit-comparison',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMigrationRoute = AuthedAdminMigrationRouteImport.update({
  id: '/admin/migration',
  path: '/admin/migration',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminHoursReportRoute = AuthedAdminHoursReportRouteImport.update({
  id: '/admin/hours-report',
  path: '/admin/hours-report',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAnnouncementsRoute =
  AuthedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/copsmart': typeof CopsmartRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/dispatch': typeof AuthedDispatchRoute
  '/forms': typeof AuthedFormsRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/profile': typeof AuthedProfileRoute
  '/resources': typeof AuthedResourcesRoute
  '/roles': typeof AuthedRolesRoute
  '/roster': typeof AuthedRosterRoute
  '/schedule': typeof AuthedScheduleRouteWithChildren
  '/training': typeof AuthedTrainingRoute
  '/vehicles': typeof AuthedVehiclesRoute
  '/api/notify': typeof ApiNotifyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/announcements': typeof AuthedAdminAnnouncementsRoute
  '/admin/hours-report': typeof AuthedAdminHoursReportRoute
  '/admin/migration': typeof AuthedAdminMigrationRoute
  '/admin/unit-comparison': typeof AuthedAdminUnitComparisonRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/schedule/print': typeof AuthedSchedulePrintRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/copsmart': typeof CopsmartRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/dispatch': typeof AuthedDispatchRoute
  '/forms': typeof AuthedFormsRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/profile': typeof AuthedProfileRoute
  '/resources': typeof AuthedResourcesRoute
  '/roles': typeof AuthedRolesRoute
  '/roster': typeof AuthedRosterRoute
  '/schedule': typeof AuthedScheduleRouteWithChildren
  '/training': typeof AuthedTrainingRoute
  '/vehicles': typeof AuthedVehiclesRoute
  '/api/notify': typeof ApiNotifyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/announcements': typeof AuthedAdminAnnouncementsRoute
  '/admin/hours-report': typeof AuthedAdminHoursReportRoute
  '/admin/migration': typeof AuthedAdminMigrationRoute
  '/admin/unit-comparison': typeof AuthedAdminUnitComparisonRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/schedule/print': typeof AuthedSchedulePrintRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/copsmart': typeof CopsmartRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/dispatch': typeof AuthedDispatchRoute
  '/_authed/forms': typeof AuthedFormsRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/resources': typeof AuthedResourcesRoute
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/roster': typeof AuthedRosterRoute
  '/_authed/schedule': typeof AuthedScheduleRouteWithChildren
  '/_authed/training': typeof AuthedTrainingRoute
  '/_authed/vehicles': typeof AuthedVehiclesRoute
  '/api/notify': typeof ApiNotifyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authed/admin/announcements': typeof AuthedAdminAnnouncementsRoute
  '/_authed/admin/hours-report': typeof AuthedAdminHoursReportRoute
  '/_authed/admin/migration': typeof AuthedAdminMigrationRoute
  '/_authed/admin/unit-comparison': typeof AuthedAdminUnitComparisonRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/schedule/print': typeof AuthedSchedulePrintRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/copsmart'
    | '/demo'
    | '/features'
    | '/login'
    | '/privacy'
    | '/product'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/dashboard'
    | '/dispatch'
    | '/forms'
    | '/leaderboard'
    | '/profile'
    | '/resources'
    | '/roles'
    | '/roster'
    | '/schedule'
    | '/training'
    | '/vehicles'
    | '/api/notify'
    | '/email/unsubscribe'
    | '/admin/announcements'
    | '/admin/hours-report'
    | '/admin/migration'
    | '/admin/unit-comparison'
    | '/admin/users'
    | '/schedule/print'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/copsmart'
    | '/demo'
    | '/features'
    | '/login'
    | '/privacy'
    | '/product'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/dashboard'
    | '/dispatch'
    | '/forms'
    | '/leaderboard'
    | '/profile'
    | '/resources'
    | '/roles'
    | '/roster'
    | '/schedule'
    | '/training'
    | '/vehicles'
    | '/api/notify'
    | '/email/unsubscribe'
    | '/admin/announcements'
    | '/admin/hours-report'
    | '/admin/migration'
    | '/admin/unit-comparison'
    | '/admin/users'
    | '/schedule/print'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/contact'
    | '/copsmart'
    | '/demo'
    | '/features'
    | '/login'
    | '/privacy'
    | '/product'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/_authed/dashboard'
    | '/_authed/dispatch'
    | '/_authed/forms'
    | '/_authed/leaderboard'
    | '/_authed/profile'
    | '/_authed/resources'
    | '/_authed/roles'
    | '/_authed/roster'
    | '/_authed/schedule'
    | '/_authed/training'
    | '/_authed/vehicles'
    | '/api/notify'
    | '/email/unsubscribe'
    | '/_authed/admin/announcements'
    | '/_authed/admin/hours-report'
    | '/_authed/admin/migration'
    | '/_authed/admin/unit-comparison'
    | '/_authed/admin/users'
    | '/_authed/schedule/print'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CopsmartRoute: typeof CopsmartRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiNotifyRoute: typeof ApiNotifyRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copsmart': {
      id: '/copsmart'
      path: '/copsmart'
      fullPath: '/copsmart'
      preLoaderRoute: typeof CopsmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify': {
      id: '/api/notify'
      path: '/api/notify'
      fullPath: '/api/notify'
      preLoaderRoute: typeof ApiNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vehicles': {
      id: '/_authed/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthedVehiclesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/training': {
      id: '/_authed/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthedTrainingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roster': {
      id: '/_authed/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthedRosterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources': {
      id: '/_authed/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthedResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/forms': {
      id: '/_authed/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthedFormsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dispatch': {
      id: '/_authed/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthedDispatchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/schedule/print': {
      id: '/_authed/schedule/print'
      path: '/print'
      fullPath: '/schedule/print'
      preLoaderRoute: typeof AuthedSchedulePrintRouteImport
      parentRoute: typeof AuthedScheduleRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/unit-comparison': {
      id: '/_authed/admin/unit-comparison'
      path: '/admin/unit-comparison'
      fullPath: '/admin/unit-comparison'
      preLoaderRoute: typeof AuthedAdminUnitComparisonRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/migration': {
      id: '/_authed/admin/migration'
      path: '/admin/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AuthedAdminMigrationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/hours-report': {
      id: '/_authed/admin/hours-report'
      path: '/admin/hours-report'
      fullPath: '/admin/hours-report'
      preLoaderRoute: typeof AuthedAdminHoursReportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/announcements': {
      id: '/_authed/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedScheduleRouteChildren {
  AuthedSchedulePrintRoute: typeof AuthedSchedulePrintRoute
}

const AuthedScheduleRouteChildren: AuthedScheduleRouteChildren = {
  AuthedSchedulePrintRoute: AuthedSchedulePrintRoute,
}

const AuthedScheduleRouteWithChildren = AuthedScheduleRoute._addFileChildren(
  AuthedScheduleRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDispatchRoute: typeof AuthedDispatchRoute
  AuthedFormsRoute: typeof AuthedFormsRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedResourcesRoute: typeof AuthedResourcesRoute
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedRosterRoute: typeof AuthedRosterRoute
  AuthedScheduleRoute: typeof AuthedScheduleRouteWithChildren
  AuthedTrainingRoute: typeof AuthedTrainingRoute
  AuthedVehiclesRoute: typeof AuthedVehiclesRoute
  AuthedAdminAnnouncementsRoute: typeof AuthedAdminAnnouncementsRoute
  AuthedAdminHoursReportRoute: typeof AuthedAdminHoursReportRoute
  AuthedAdminMigrationRoute: typeof AuthedAdminMigrationRoute
  AuthedAdminUnitComparisonRoute: typeof AuthedAdminUnitComparisonRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDispatchRoute: AuthedDispatchRoute,
  AuthedFormsRoute: AuthedFormsRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedResourcesRoute: AuthedResourcesRoute,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedRosterRoute: AuthedRosterRoute,
  AuthedScheduleRoute: AuthedScheduleRouteWithChildren,
  AuthedTrainingRoute: AuthedTrainingRoute,
  AuthedVehiclesRoute: AuthedVehiclesRoute,
  AuthedAdminAnnouncementsRoute: AuthedAdminAnnouncementsRoute,
  AuthedAdminHoursReportRoute: AuthedAdminHoursReportRoute,
  AuthedAdminMigrationRoute: AuthedAdminMigrationRoute,
  AuthedAdminUnitComparisonRoute: AuthedAdminUnitComparisonRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CopsmartRoute: CopsmartRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiNotifyRoute: ApiNotifyRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
